upptime/uptime-monitor

package-lock.json
package.json
src/index.ts
src/site.ts

🚀 Opening a pull request for this branch

Update from feature-site-generator

---

package-lock.json
package.json
src/helpers/notifme-sdk.d.ts
src/helpers/notifme.ts
src/update.ts

🚀 Opening a pull request for this branch

Update from feature-notifications

---

src/helpers/notifme.ts

Fix for https://github.com/upptime/upptime/issues/352

Fix for underscope issue

---

src/site.ts

Fixes https://github.com/upptime/upptime/issues/454
Feedback welcome, my typescript experience is zero :-).

 Configure shelljs to fail on failure

---

src/helpers/notifme.ts

Add Lark Bot Privider
This is Bot Doc https://www.larksuite.com/hc/zh-CN/articles/360048487736#3.%20%E5%8F%91%E9%80%81%E6%9B%B4%E4%B8%AA%E6%80%A7%E5%8C%96%E7%9A%84%E6%B6%88%E6%81%AF
This is Message Doc
https://open.larksuite.com/document/ukTMukTMukTM/uADOwUjLwgDM14CM4ATN

✨ Add Lark Provider

---

package.json
src/interfaces.ts
src/update.ts

This PR adds a websocket check to the monitor. It will either connect and wait for data to be returned, or connect and send a message and wait for data to be returned.

Add WebSocket check

---

src/helpers/workflows.ts
src/workflows/summary.yml

Fixes https://github.com/upptime/upptime/issues/559

Update workflow references

---

src/update.ts

Updated version of #180
Messages use secret "NOTIFICATIONS_DOWN_MESSAGE" and "NOTIFICATIONS_UP_MESSAGE"

Custom downtime & uptime messages.

---

src/helpers/notifme.ts

This PR contains Microsoft Teams webhook integration. Fixes upptime/upptime#285 and upptime/upptime#627.
| Environment variable             | Value               |
| -------------------------------- | ------------------- |
| `NOTIFICATION_TEAMS`             | Set to `true`       |
| `NOTIFICATION_TEAMS_WEBHOOK_URL` | Teams webhook URL   |
Microsoft Teams webhook reference: [Create Incoming Webhooks](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook).
Documentation PR: upptime/upptime.js.org#36

✨ Add Microsoft Teams integration

---

src/update.ts

This PR fixes typo at status up message.

✏️ Fix typo at status up message

---

src/helpers/notifme.spec.ts
src/helpers/notifme.ts

This PR adds support for notifications in [Zulip](https://zulip.com/).

:sparkles: Add Zulip integration

---

.github/workflows/build.yml
.github/workflows/node.yml
.github/workflows/release.yml

This should upgrade to Node version 18 (the latest stable version) which should resolve the problem.

Issue #694: Upgraded to Node version 18 in the build.

---

dist/helpers/workflows.js
package-lock.json
src/helpers/workflows.ts

Add default token (`github.token`) as a fallback for `secrets.GH_PAT`, which allows using a template without generating new `GH_PAT`.
See discussion at [upptime/upptime#731](https://github.com/upptime/upptime/discussions/731)

Add fallback GitHub token

---

.github/workflows/build.yml
.github/workflows/node.yml
.github/workflows/release.yml

:bug: Upgrade to Node.js v18

---

.github/workflows/build.yml
.github/workflows/node.yml
.github/workflows/release.yml
package.json

:sparkles: Use Node.js v16 with updated dependencies

---

src/update.ts

This PR resolves https://github.com/upptime/upptime/issues/872

Only add a maintenance event if start date has passed

---

src/update.ts

:sparkles: Add support for Action secrets everywhere

---

.github/workflows/build.yml
.github/workflows/node.yml
.github/workflows/release.yml
action.yml
package-lock.json
package.json
src/automations.ts

As asked for in https://github.com/upptime/uptime-monitor/pull/239 here's a PR to update `node-version`.
This PR fixes issue https://github.com/upptime/upptime/issues/969

👷 Use current node-version 20

---

src/helpers/workflows.ts

(see also https://github.com/upptime/upptime/pull/982)

👷 Renovate: Update peaceiris/actions-gh-pages action to v4

---

src/helpers/notifme.ts

Gotify is an extremely lightweight notification project, I love it, so I added it as a notification option. 
And also, this PR solved [this discussion](https://github.com/orgs/upptime/discussions/622).

Add Gotify as notification option

---

.npmrc
package-lock.json
package.json
src/interfaces.ts
src/update.ts

Added the ability to set `"ssl"` as a checker.  It will fail if the SSL certificate expires in < 7 days.

feat: added SSL checker (if SSL cert expires < 7 days then it fails
