upptime/uptime-monitor

- package-lock.json
- src/helpers/config.ts
Function `yaml.safeLoad` is removed in js-yaml version 4. `yaml.load` is safe by default in version 4
This should prevent failures like this one - https://github.com/mikechernev/uptime-checks/runs/1651350890?check_suite_focus=true
> Change `yaml.safeLoad` to `yaml.load` because it is breaking the Update Template CI jobs

- src/graphs.ts
- src/helpers/calculate-uptime.ts
- src/update.ts
Similarly to https://github.com/upptime/uptime-monitor/pull/86, the `safeLoad` function should be replaced for all other CI's
> Replace all instances of `yaml.safeLoad` because all other CI's are broken now

- dist/helpers/request.js
- src/helpers/request.ts
Since zero is "falsy", it would not be accepted and the default of 3
would be used. This change verifies that the input is an integer value
instead, which is more robust and handles this use case.
Fixes upptime/upptime#127
> Accept a 0 value for maxRedirects

- package-lock.json
- package.json
Solution is to bump [@octokit/rest](https://github.com/octokit/rest.js) dependency.
Also had to update `node-libcurl`.
Fixes upptime/upptime#288
Fixes upptime/upptime#296
Tested here : https://github.com/betagouv/api-particulier-status/runs/2351594726?check_suite_focus=true
> Fix bug calling Github API using outdated @octokit/rest

- src/interfaces.ts
- src/update.ts
Ref https://github.com/upptime/upptime/discussions/527
Adds tags property to sites and sets the tags as labels on new issues. Makes it possible to mark downtime issues with for instance "test" or "prod"
> Add custom tags to issues created by uptime-monitor

- src/summary.ts
_Fixes https://github.com/upptime/upptime/discussions/552_
Switched to DuckDuckGo favicon API, because GitHub favicon API is no longer in operation.
> Changed favicon api

- src/helpers/constants.ts
Fix upptime/upptime#635
Use `ubuntu-20.04` to aviod the deprecated warning from Github Action.
Ref: GitHub Action announce as actions/runner-images#6002
> CI: Use `ubuntu-20.04` to aviod the deprecated warning from Github Action

- src/update.ts
When using Upptime with a `GITHUB_TOKEN` _(because a PAT is scary - see https://github.com/upptime/upptime/discussions/231)_, Upptime logs errors and fails when trying to automatically close an issue. This is because github actions are not allowed to work with locked issues. 
Oddly though, they Github Actions can lock/unlock issues, so this change enables that workaround. See https://github.com/orgs/community/discussions/25230#discussioncomment-3246970
Here's the problem I hit -- my company's website had a false positive - Upptime [opened an issue on Cycle 1](https://github.com/quickcode-ai/quickcode-status/runs/8246248036?check_suite_focus=true#step:3:27), then went to [close it 5m later on Cycle 2, but failed.](https://github.com/quickcode-ai/quickcode-status/runs/8246420766?check_suite_ …
> Unlock issues while working with them so Upptime+GITHUB_TOKEN can close issues it creates

- src/helpers/notifme.ts
This is an emergency update to #193 by:
1. Removing `MisskeyProvider` and the need to use `misskey` inside channels list. This is because we don't intend to use multiple integration strategies yet. (and this mistake may cause into import errors)
2. Rename `NOTIFICATION_MISSKEY_INSTANCEURL` to `NOTIFICATION_MISSKEY_INSTANCE_URL` to match environment variable conventions
> fix: Misskey integration

- src/helpers/notifme.ts
This pull request adds support for sending posts (or "toots") for Mastodon servers in a similar fashion to Misskey. Direct messages are also possible by setting the post visibility to `direct`.
> feat: Add Mastodon integration

- src/helpers/request.ts
- src/interfaces.ts
Currently the verbose option in `libcurl` is forced to `false`.
I am currently getting timeouts from my uptime checks but the only error I see is `Got an error (on error) [Error: Timeout was reached]`. [You can see the log in my action here.](https://github.com/AceCentre/upptime/actions/runs/3405937283/jobs/5664272649#step:3:22)
I want to know more about what is happening in `libcurl` so I can figure out what is causing the error. However, I can't see into whats going on inside `libcurl` because the logging is forced off.
This PR allows you to turn on verbose logging per site.
> Allow verbose logging in libcurl

- action.yml
Node.js 12 actions are deprecated.
For more information see:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the following actions to use Node.js 16: upptime/uptime-monitor@v1.29.0
> ⬆️  fix deprecation warning for Node.js 12

- src/update.ts
This "fixes" the following line on Uptime CI checks:
```
Checking https://DOMAIN
Current status undefined up 2023-06-04T14:49:10.000Z
Result from test 200 0.982486
```
This can also been seen on the upptime repos action runs:
https://github.com/upptime/upptime/actions/runs/5171412631/jobs/9314941347#step:3:14
> Use slugify if site has no slug

- README.md
When working on something else I found the contribution guidelines and code of conduct had broken links. I fixed that. No code was changed. The other pull request I made for this can be disregarded. I added some code changes because I was not paying attention. 
Have a great day!
> Fixed broken links to contribution guidelines and code of conduct

- src/update.ts
Hi, 
**What does it do:**
After having a few downtime incidents I wondered how long it took for the downtime to resolve itself.  Thats why I figured to add the duration of the incident to the comment that Upptime posts once a website comes back online. 
I did it quite hacky but that is mainly because I could not find where functions go in the repo. Please let me know if: 
- You'd like to have that feature added then I'll clean it up, and make sure to test properly
- Where you'd like these kind of generic helper functions (finding a timedelta between 2 timestamps)
> Adding time delta to the 'resolved' comment 

- src/helpers/constants.ts
- src/helpers/environment.ts
- src/update.ts
Now it is possible to inject randomized numbers into HTTP requests. Specifically, the `$DYNAMIC_RANDOM_NUMBER` placeholders in the request URL or body will be substituted with actual random values. The range for these numbers can be configured using the `RANDOM_MIN` and `RANDOM_MAX` environment variables, which default to `0` and `1000000`, respectively.
Discussion: https://github.com/upptime/upptime/discussions/857
> Introduce dynamic random numbers support in HTTP requests

- src/helpers/notifications.ts
- src/helpers/notifme.ts
Google Chat supports [webhooks](https://developers.google.com/chat/how-tos/webhooks) in their Spaces group chat option. The structure is a flat JSON payload:
```json
{
"text": "message"
}
```
This PR adds the option in a very similar style to the existing Discord notifications.
> Add Google Chat Notifications Webhook Support

- src/update.ts
Per https://github.com/upptime/upptime/discussions/888
> feat: add support for pinging IPv6 addresses and hostnames via `ipv6: true`

- src/update.ts
It appears your rewrite caused this feature to not work.
See our comment here <https://github.com/upptime/uptime-monitor/pull/231#issuecomment-1854474974>.
> fix: fixed ipv6 check properly

- src/site.ts
By ignoring auditing, funding, and warning messages the action output becomes more succinct and slightly faster. Here's the current output, with the lines that will be removed:
```diff
added 51 packages, and audited 52 packages in 3s
-found 0 vulnerabilities
-npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
-npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
-npm WARN deprecated sapper@0.29.3: SvelteKit is the successor to Sapper - https://kit.svelte.dev/
added 1087 packages, removed 1 package, and audited 1605 packages in 44s
-129 packages are looking for funding
-  run `npm fund` for details
-86 vulnerabilities …
```
> Make npm installs quieter and faster

- .github/workflows/build.yml
- .github/workflows/node.yml
- .github/workflows/release.yml
- dist/helpers/workflows.js
- src/helpers/workflows.ts
Use latest major version of [actions/setup-node](https://github.com/actions/setup-node) for GitHub Actions
> 👷 use latest major version for actions/setup-node

- src/helpers/notifme.ts
With this PR, users can fill in multiple chat ids into NOTIFICATION_TELEGRAM_CHAT_ID like `xxxxx, xxxxx`.
Feature was requested there: https://github.com/orgs/upptime/discussions/956
> Add support for multiple NOTIFICATION_TELEGRAM_CHAT_ID

- src/helpers/notifme.ts
Add the support of custom webhooks as notification endpoint
This would be the first step to solve [upptime discussions 191](https://github.com/orgs/upptime/discussions/191)
It uses `NOTIFICATION_WEBHOOK` boolean and
`NOTIFICATION_WEBHOOK_URL` for the URL
Other configuration could be possible when this PR gets merged.
Thanks ✌️
> feat: Add custom webhook as notification option

- src/helpers/notifme.ts
Similar to <https://github.com/upptime/uptime-monitor/blob/0f5dcab55c8349820fc0edb32373b4de25e792cd/src/helpers/notifme.ts#L334-L345> we added support for SMS sending to multiple numbers.
> feat: send to multiple SMS numbers separated by comma

- package-lock.json
- package.json
- src/interfaces.ts
- src/update.ts
This PR adds support for [Globalping](https://globalping.io), which allows you to run checks from any location around the world.
Two new properties are added for sites:
- `type` (can be "local" or "globalping", defaults to "local");
- `location` Location to run the check from. defaults to "world"
Examples:
Simple GET request via Globalping from California.
```yaml
sites:
- name: Google
url: https://www.google.com
type: globalping
location: california # Location to run the check from. Optional. Default is "World"
```
Ping measurement via Globalping from Germany.
```yaml
sites:
- name: Google
url: https://www.google.com
type: globalping
check: "tcp-ping"
location: Germany
```
> feat: add globalping support
